### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by larsenv** [hacks-guide/Guide_Wii#15]
I own Wii.guide as it's part of RiiConnect24. I'm willing to negotiate on redirecting our site to yours because it's honestly much nicer if you compare it to our guide, but I have a couple of questions.

- Is there going to be opportunities to do a translation of the guide?
- Why is the RiiTag page completely removed? I thought it would be because of the USB Loaders being associated to warez, but there's a page on that.
- Why is your Discord the one which is recommended for support?

**Comment by DyingHynixMLC** [comment]
1: I believe there should be soon.
2: Probably because NH is not associated with RC24 
3: This is a NH hosted guide (afaik), so why should we redirect to some other place like RC24 since we already have a #legacy-systems channel?

**Comment by ItzSwirlz** [comment]
- there is a hacks.guide-hosted-crowdin server for translations
- maybe because its not Wii-specific? That's my guess?
- The NH discord now has a #Wii-assistance channel. Definitely good IMO because then it keeps the assistance for all the consoles in one place

**Comment by lifehackerhansol** [comment]
Hello Larsen, thanks for reaching out.

I suppose I'll get right to the questions:

1. We have a translation platform set up at <https://hacks-guide.crowdin.com/>. It's only been open for about a day or so, and we're figuring out internally how it will be handled, but the platform is there for people who want a head start at it.
1. During our process of working with the Wii we have decided to remove unnecessary pages from the guide. Note that this process is still a work-in-progress, but to put shortly, RiiTag simply has nothing to do with getting one's console hacked. It's certainly a fun thing one can do with soft-mods, but we decided it wasn't of high importance. There are other pages that are also planned to be removed or moved elsewhere.
    - Note we do have plans to migrate them to <https://wiki.hacks.guide/>. This is where all the "extras" of console hacking tutorials are currently written for other consoles supported by Nintendo Homebrew, and the Wii will follow suit shortly.
    - That said, as a suggestion from me personally, I would very much recommend that RiiConnect24 hosts the tutorials for their services on their branded domain (rc24.xyz), as, frankly, it is your service, people should be visiting your service's website and not a generic guide.
1. We have put together a proper support channel and a team of volunteer helpers to streamline support for the Wii console. We feel that our current organization is sufficient for handling help and support for end users, as well as gather feedback from users directly. In other words, now that we (Nintendo Homebrew) are working on a Wii guide, we are putting the needed work to make sure the support aspect is also covered during that process.

In regards to cooperation... I feel that it is too early for us to discuss this matter. It has only been one day since our launch. Surely this isn't enough time for your team to jump the gun and transfer control over? I think it's best that we stay as separate entities for the time being.

I hope this response answered all your concerns.
