### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by merwok** [hacks-guide/Guide_Wii#83]
English and Italian versions are on the website: are the other translations published somewhere?

What is the process to follow to help with translations?

Thanks!

**Comment by playerjmr** [comment]
> English and Italian versions are on the website: are the other translations published somewhere?
> 
> What is the process to follow to help with translations?
> 

Hi, you can find and assist with translations [here](https://hacks-guide.crowdin.com/wii)

Translations are disabled until enough of the guide has been translated for that language, which is why italian is the only one available currently. The guide itself is fairly new, being forked from the original wii.guide.

**Comment by playerjmr** [comment]
If a language you want to translate to is not there, we might be able to add it for you.

**Comment by merwok** [comment]
I see the french translation is incomplete. I will contribute on crowdin when I have the time!

**Comment by smh5972** [comment]
> אם שפה שאליה ברצונך לתרגם אינה קיימת, ייתכן שנוכל להוסיף אותה עבורך.

I want to translate into Hebrew. Can I add that?
